language: c
os:
    - linux

install:
    curl -sL https://raw.githubusercontent.com/k-hosokawa/pac/master/install | sudo bash

script:
    - curl -L -O https://raw.githubusercontent.com/k-hosokawa/pac/master/sample.toml
    - mkdir -p ~/.config/pac/
    - mv sample.toml ~/.config/pac/config.toml
    - /usr/local/bin/pac src install
