[brew]
tap = ["homebrew/bundle", "homebrew/cask", "homebrew/services"]
cask = ["appcleaner", "mactex", "the-unarchiver", "xquartz"]
pkgs = [
    "autoconf",
    "bazel",
    "cmake", "coreutils", "ctags",
    "direnv", "diff-so-fancy",
    "ffmpeg", "fish", "fontconfig", "fontforge",
    "gawk", "git", "glib","graphviz",
    "hub",
    "imagemagick",
    "jq",
    "lame",
    "mariadb", "mecab", "mecab-ipadic",
    "neovim", "nkf", "nmap", "node", "nodebrew",
    "opencv3", "open-jtalk", "openssl",
    "pkg-config", "protobuf", "python",
    "qt",
    "rbenv", "readline", "reattach-to-user-namespace", "ripgrep",
    "ruby-build", "rust",
    "shelcheck", "sqlite", "swig",
    "terminal-notifier", "tmux", "tree",
    "w3m", "wget","zsh-completions",
]
[[brew.optionalPkgs]]
    pkg = "go"
    args = ["--cross-compile-common"]

[[brew.optionalPkgs]]
    pkg = "htop"
    args = ["--with-ncurses"]

[[brew.optionalPkgs]]
    pkg = "llvm"
    args = ["--with-clang"]

[[brew.optionalPkgs]]
    pkg = "zsh"
    args = ["--disable-etcdir"]

[[brew.optionalPkgs]]
    pkg = "cema-sp/tap/alacritty"
    args = ["--HEAD"]

[go]
repos = [
    "k-hosokawa/powerline-go",
    "motemen/ghq",
    "peco/peco",
    "mattn/memo",
]

[src]
[[src.pkg]]
repo = "simonwhitaker/gibo"

[[src.pkg]]
repo = "b4b4r07/zsh-vimode-visual"

[[src.pkg]]
repo = "zsh-users/zsh-completions"

[[src.pkg]]
repo = "zsh-users/zsh-syntax-highlighting"

[[src.pkg]]
repo = "b4b4r07/enhancd"

[[src.pkg]]
repo = "Valodim/zsh-curl-completion"

[[src.pkg]]
repo = "b4b4r07/zsh-gomi"

[[src.pkg]]
repo = "b4b4r07/zsh-history"

[[src.pkg]]
repo = "marzocchi/zsh-notify"

[[src.pkg]]
repo = "b4b4r07/emoji-cli"

[[src.pkg]]
repo = "mrowa44/emojify"

[[src.pkg]]
repo = "simonwhitaker/gibo"

[[src.pkg]]
repo = "Fakerr/git-recall"

[[src.pkg]]
repo = "jhawthorn/fzy"
build = ["make"]
onCmd = "fzy"

[[src.pkg]]
repo = "saghul/pythonz"
doClone = false
freeze = true
build = [
    "curl -kLO https://raw.github.com/saghul/pythonz/master/pythonz-install",
    "chmod +x pythonz-install",
    "./pythonz-install",
]
buildEnv = ["PYTHONZ_ROOT=__GPMW_HOME__"]

[[src.pkg]]
repo = "jwilm/alacritty"
onOs = "darwin"
build = [
    "make app",
]
onApp = "target/release/osx/Alacritty.app"
